/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UserAccessRouteImport } from './routes/user-access'
import { Route as StaffRouteImport } from './routes/staff'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as PayrollRouteImport } from './routes/payroll'
import { Route as LogisticsRouteImport } from './routes/logistics'
import { Route as LoginRouteImport } from './routes/login'
import { Route as InventoryRouteImport } from './routes/inventory'
import { Route as IndexRouteImport } from './routes/index'

const UserAccessRoute = UserAccessRouteImport.update({
  id: '/user-access',
  path: '/user-access',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffRoute = StaffRouteImport.update({
  id: '/staff',
  path: '/staff',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const PayrollRoute = PayrollRouteImport.update({
  id: '/payroll',
  path: '/payroll',
  getParentRoute: () => rootRouteImport,
} as any)
const LogisticsRoute = LogisticsRouteImport.update({
  id: '/logistics',
  path: '/logistics',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const InventoryRoute = InventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/inventory': typeof InventoryRoute
  '/login': typeof LoginRoute
  '/logistics': typeof LogisticsRoute
  '/payroll': typeof PayrollRoute
  '/settings': typeof SettingsRoute
  '/staff': typeof StaffRoute
  '/user-access': typeof UserAccessRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/inventory': typeof InventoryRoute
  '/login': typeof LoginRoute
  '/logistics': typeof LogisticsRoute
  '/payroll': typeof PayrollRoute
  '/settings': typeof SettingsRoute
  '/staff': typeof StaffRoute
  '/user-access': typeof UserAccessRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/inventory': typeof InventoryRoute
  '/login': typeof LoginRoute
  '/logistics': typeof LogisticsRoute
  '/payroll': typeof PayrollRoute
  '/settings': typeof SettingsRoute
  '/staff': typeof StaffRoute
  '/user-access': typeof UserAccessRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/inventory'
    | '/login'
    | '/logistics'
    | '/payroll'
    | '/settings'
    | '/staff'
    | '/user-access'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/inventory'
    | '/login'
    | '/logistics'
    | '/payroll'
    | '/settings'
    | '/staff'
    | '/user-access'
  id:
    | '__root__'
    | '/'
    | '/inventory'
    | '/login'
    | '/logistics'
    | '/payroll'
    | '/settings'
    | '/staff'
    | '/user-access'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  InventoryRoute: typeof InventoryRoute
  LoginRoute: typeof LoginRoute
  LogisticsRoute: typeof LogisticsRoute
  PayrollRoute: typeof PayrollRoute
  SettingsRoute: typeof SettingsRoute
  StaffRoute: typeof StaffRoute
  UserAccessRoute: typeof UserAccessRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/user-access': {
      id: '/user-access'
      path: '/user-access'
      fullPath: '/user-access'
      preLoaderRoute: typeof UserAccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff': {
      id: '/staff'
      path: '/staff'
      fullPath: '/staff'
      preLoaderRoute: typeof StaffRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payroll': {
      id: '/payroll'
      path: '/payroll'
      fullPath: '/payroll'
      preLoaderRoute: typeof PayrollRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logistics': {
      id: '/logistics'
      path: '/logistics'
      fullPath: '/logistics'
      preLoaderRoute: typeof LogisticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventory': {
      id: '/inventory'
      path: '/inventory'
      fullPath: '/inventory'
      preLoaderRoute: typeof InventoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  InventoryRoute: InventoryRoute,
  LoginRoute: LoginRoute,
  LogisticsRoute: LogisticsRoute,
  PayrollRoute: PayrollRoute,
  SettingsRoute: SettingsRoute,
  StaffRoute: StaffRoute,
  UserAccessRoute: UserAccessRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
